#! /usr/bin/env python

import sys
import subprocess
import daemon
import psutil

def main():

    inhibit = ['systemd-inhibit',
        '--what=idle:sleep:shutdown:handle-lid-switch',
        'sleep',
        'infinity']

    if sys.argv[1] == 'login':
        for proc in psutil.process_iter():
            if inhibit == proc.cmdline():
                return

        print "Starting inhibitor"
        with daemon.DaemonContext():
            subprocess.call(inhibit)
    elif sys.argv[1] == 'logout':
        terms = 0
        for usr in psutil.users():
            if usr.host != 'localhost':
                terms += 1
                if terms > 1:
                    return

        print "Stopping inhibitor"
        subprocess.call(['pkill', '-f', ' '.join(inhibit)])

if __name__ == '__main__':
    sys.exit(main())
